### ISSUE TITLE
Expose message objects as first class packets!

### ISSUE THREAD

**Issue by tgoodlet** [codypiersall/pynng#21]
As per [gitter discussion](https://gitter.im/nanomsg/nanomsg?at=5c32a2f01491b27876d0ae5c) between @gdamore and I, message objects should be exposed for a variety of reasons:
- figuring out what pipes to use for multiplexing in polyamorous `Pair1` socket comms
- accessing TLS related certificate info

@gdamore also says the [implementation here](https://github.com/codypiersall/pynng/blob/master/pynng/_aio.py#L162) may cause *use after free* crashes.

**Comment by codypiersall** [comment]
First off, I _completely_ agree that nng_msg should be exposed in the API, so this is a great issue for tracking that.

Maybe `Socket` et. al could grow some extra methods: `recv_message` and `arecv_message`.  The underlying pipe of the message would be exposed via a `pipe` attribute, and the *buffer* will be exposed via the buffer attribute.  I *think* this should be pretty straightforward to implement.  It should also avoid extra copies.

Second and importantly, there's not a potential for use after free from this implementation: it's okay that the msg is free'd, because the underlying buffer is copied by calling the bytes constructor [here](https://github.com/codypiersall/pynng/blob/master/pynng/_aio.py#L166).

TLS connections aren't supported by pynng yet, but we're tracking it in #20.

**Comment by gdamore** [comment]
So I am happy to hear that there is no use after free. But of course the
downside is an extra alloc and data copy. Passing around the message would
avoid the need for that.

**Comment by codypiersall** [comment]
Agreed!  Thinking about this a little more, instead of growing new methods, it would be better if the existing `recv` and `arecv` return an object that implements the [buffer protocol](https://docs.python.org/3/c-api/buffer.html).  This object would be the Python wrapper of nng's nng_msg type.  The the obvious, convenient API would also be the correct API.  I think this will require writing a little custom extension module, but it would be a pretty simple one.  I don't think a pure Python class can implement the buffer protocol.  I'd be happy to be wrong about that though.

There may be some code using pynng that relies on `isinstance(sock.recv(), bytes)` being True, but using a pre-1.0 library, hopefully people are prepared for a small amount of breakage.  In most ways, an object implementing the buffer protocol acts like a bytes object, so most code shouldn't notice the difference... I think.

**Comment by codypiersall** [comment]
After working on this a bit today, I'm torn about the best approach.  The convenience of `send()` and `recv()` (and the async equivalents) returning bytes is really high, actually.  Right now I'm leaning toward new `send_msg` and `recv_msg` (and async equivalents) methods.  This will return a Message object, and the buffer could be accessed with a `buffer` attribute.  Using cffi, we _can_ actually return an object that implements the buffer protocol, and there won't be an extra copy.

I'm still chewing this over.  I started writing the extension module, but it turns out that an object that acts exactly like a `bytes` object without actually being a `bytes` object is still pretty involved :-).

**Comment by codypiersall** [comment]
This is implemented in #24 (commit e47d05e1f44b27bbe84f34498742ac48441dc136)
