### ISSUE TITLE
pynng does not work on Python 2.7

### ISSUE THREAD

**Issue by davesliu** [codypiersall/pynng#26]
ldw@ubuntu:~$ git clone https://github.com/codypiersall/pynng
Cloning into 'pynng'...
remote: Enumerating objects: 61, done.
remote: Counting objects: 100% (61/61), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 682 (delta 28), reused 43 (delta 18), pack-reused 621
Receiving objects: 100% (682/682), 146.12 KiB | 261.00 KiB/s, done.
Resolving deltas: 100% (422/422), done.
ldw@ubuntu:~$ cd pynng
ldw@ubuntu:~/pynng$ pip install -e .
Obtaining file:///home/ldw/pynng
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/ldw/pynng/setup.py", line 27
        major, minor, *_ = sys.version_info
                      ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/ldw/pynng/
ldw@ubuntu:~/pynng$ python --version
Python 2.7.15rc1
ldw@ubuntu:~/pynng$ uname -a
Linux ubuntu 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
ldw@ubuntu:~/pynng$

======================
I want to install pynng on ubuntu18.04 OS with python2.7, but failed with above log info.
Could you help to see what's the issue for the setup.py ?

**Comment by davesliu** [comment]
I solved the issue by change the line 27 and line 96 (remove the encoding='UTF-8') of setup.py and it works now
===============
...
 27         major, minor = sys.version_info
...
 96 with open('README.md', 'r' ) as f:
...
================

**Comment by davesliu** [comment]
ubuntu:~/pynng$ pip --version
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)

I use above pip 9.0.1 and python 2.7, still a little confused that the default setup.py will fail on ubuntu18

**Comment by codypiersall** [comment]
Hi @davesliu,

Thanks for opening the issue.  Python 2 is not supported by pynng.  In particular, since we are using async/await syntax which was [added in Python 3.5](https://www.python.org/dev/peps/pep-0492/), even if the setup script worked in Python 2, installation of the library would still fail.  Since Python 2 is being EOL'd at the end of this year I'm not really interested in supporting it.

I'm going to leave this issue open, though, so people can find it.  If lots of other people want Python 2 support, maybe we can figure out what to do.  The most difficult thing is that we're using async/await in places, I think.  There may be other issues I'm not thinking of right now though.

**Comment by davesliu** [comment]
@codypiersall  Thanks for your info. So could you help to revise the README to change it to "pip3 install pynng" ?

**Comment by codypiersall** [comment]
Will do.
