### ISSUE TITLE
macOS Build

### ISSUE THREAD

**Issue by neachdainn** [codypiersall/pynng#5]
The README says:

> This project does not yet know how to build for Mac, because I don't have a Mac to test on. The tricky bit is letting cffi know the correct object file to link to, and ensuring whatever the Mac equivalent of -fPIC is set when compiling.

I just successfully built this on macOS High Sierra without any issues. The only warnings were a series of linker warnings saying that some object files were built for a newer version of macOS than were being linked. I haven't tested the build beyond running `pytest` but that was also successful. I did **not** have _nng_ installed on my system before trying to build pynng.

Is there anything else you would like me to do and/or test before you're comfortable saying macOS is supported?

**Edit:** It only works with Python3 but the errors I am receiving make it seem unlikely that it a Mac-specific issue.

**Comment by codypiersall** [comment]
Thanks for testing this!  For some reason I though Macs used clang instead of gcc, so I figured nothing would work.  I'm glad it worked!

I'm going to leave this issue open until a `pip install pynng` will work on Mac.  I'm sure it won't right now, because [the latest commit](https://github.com/codypiersall/pynng/commit/db299bf2b6e137881a28c37869ce06fbba9a8362) fixed an issue with the source distribution that was causing building the nng library to fail; but I suspect it will work after I cut a new release and push the stuff to PyPI.

I didn't have plans on supporting Python 2 since it will be end-of-life'd in about a year, and the plan that I currently have for implementing #4 would, I think, not be possible on Python 2.

**Comment by neachdainn** [comment]
I do have GCC installed via Homebrew **but** I don't see where you reference GCC anywhere in the repository. If it's issues with `-fPIC` then: (1) clang also accepts that flag and (2) CMake should take care of that for you. In fact, I bet that you don't even need to add it to the `CFLAGS` in `build_nng.sh`.

**Comment by wtfuzz** [comment]
I'm able to install from git master on macOS Mojave and anaconda3. The version from PyPi did not build.

```
$ pip install git+https://github.com/codypiersall/pynng.git
Collecting git+https://github.com/codypiersall/pynng.git
  Cloning https://github.com/codypiersall/pynng.git to /private/var/folders/4z/09bmwmq13l3_nw2qhxb978h80000gn/T/pip-req-build-hwx0wz9r
Requirement already satisfied: cffi in ./anaconda3/lib/python3.7/site-packages (from pynng==0.1.3.dev1) (1.7.0)
Collecting sniffio (from pynng==0.1.3.dev1)
  Downloading https://files.pythonhosted.org/packages/ca/08/58f3b857b8bba832983e8c5dce5e3f8c677a5527e41cf61ff45effc78cae/sniffio-1.0.0-py3-none-any.whl
Requirement already satisfied: pycparser in ./anaconda3/lib/python3.7/site-packages (from cffi->pynng==0.1.3.dev1) (2.18)
Building wheels for collected packages: pynng
  Running setup.py bdist_wheel for pynng ... done
  Stored in directory: /private/var/folders/4z/09bmwmq13l3_nw2qhxb978h80000gn/T/pip-ephem-wheel-cache-2npflepe/wheels/d9/40/b3/97e674bda91b812425b1e5a86ccf3452b590d224918745d471
Successfully built pynng
twisted 18.7.0 requires PyHamcrest>=1.9.0, which is not installed.
Installing collected packages: sniffio, pynng
Successfully installed pynng-0.1.3.dev1 sniffio-1.0.0
```

**Comment by codypiersall** [comment]
Thanks for the feedback @wtfuzz.  I cut a new release tonight (v0.2.0) that should be installable via PyPI on a Mac—I'll update the README shortly.  If it's still not installable please re-open this issue.
