### ISSUE TITLE
trio example shows deprecation warnings with Trio >= 0.15.0

### ISSUE THREAD

**Issue by lilalinda** [codypiersall/pynng#65]
Trying the example for `trio` on the top-level README file [in section](https://github.com/codypiersall/pynng#using-pynng-with-an-async-framework), I get:
```
/usr/local/lib/python3.7/site-packages/pynng/_aio.py:71: TrioDeprecationWarning: trio.hazmat is deprecated since Trio 0.15.0; use trio.lowlevel instead (https://github.com/python-trio/trio/issues/476)
  token = trio.hazmat.current_trio_token()
/usr/local/lib/python3.7/site-packages/pynng/_aio.py:72: TrioDeprecationWarning: trio.hazmat is deprecated since Trio 0.15.0; use trio.lowlevel instead (https://github.com/python-trio/trio/issues/476)
  task = trio.hazmat.current_task()
/usr/local/lib/python3.7/site-packages/pynng/_aio.py:94: TrioDeprecationWarning: trio.hazmat is deprecated since Trio 0.15.0; use trio.lowlevel instead (https://github.com/python-trio/trio/issues/476)
  await trio.hazmat.wait_task_rescheduled(abort_fn)
/usr/local/lib/python3.7/site-packages/pynng/_aio.py:75: TrioDeprecationWarning: trio.hazmat is deprecated since Trio 0.15.0; use trio.lowlevel instead (https://github.com/python-trio/trio/issues/476)
  token.run_sync_soon(trio.hazmat.reschedule, task)
```
I have Trio v0.15.1 installed.

**Comment by codypiersall** [comment]
Thanks for the heads up—I'll have to ping the trio guys about the better way to do things now.

If this is something you're comfortable with issuing a PR I'd be open for it—it does use some pretty sharp edges of trio that I'm not that familiar with.  Nathaniel initially helped out with some code samples in #4, and I have to admit to not understanding them that well.

If you (or someone else) can open a PR for this that would be great.  I'm in the middle of selling/buying houses/moving which is a Whole Thing™.  Otherwise I'll hopefully be able to get to it eventually.

Again, thanks for opening this issue!

**Comment by lilalinda** [comment]
Hi Cody,

Thanks for your quick response!

I am fairly new to Trio *and* pynng, so will not jump to any PR soon.  However, I really like each approach on its own (and got my things working with each individually), so if the pain threshold becomes too high, I might try to poke at a fix.  It seems that Nathaniel is quick to deprecate things but also offers improved replacements (I just went from trio.Queue to trio.MemoryChannel) when doing so…  Hopefully the issue he referenced and the deprecation hint will give us enough to start the upgrade.

Good luck with the move and everything that is involved.  Let’s just be in touch via this issue reporting and see where things go,
Linda
